### ISSUE TITLE
Display images by folder from cloudinary

### ISSUE THREAD

**Issue by nikitamalinov** [nikitamalinov/razvedchik#22]
I have my images and folders to be managed in cloudinary. This nextjs application will talk with cloudinary to create, read, and delete photos from folders in cloudinary. From the admin page, these api operations will be sent to nextjs api endpoints that you will create that will call clouinary.

In the admin page and new nextjs api endpoints you create, I want you to implement the following:

1. list the folders and their respective images from cloudinary in the admin page. This will require you to create a nextjs api route and also add the UI to the admin page. The admin page will populate the folders and images from calling the api route
2. allow users to create a new folder in the admin page. This will also call a different nextjs api route you will create.
3. allow users to upload a photo to a selected folder in the admin page. This will also call a different nextjs api route you will create.

**Comment by diegoreis1980** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Zagal435, @EngineeringErgonomics, @yavorsky, @DwGoing, @markpking2, @fi-ma, @arjanvillon, @vvvictorlee, @nickmccurdy, @samir-acle, @stjordanis, @hr2022hr, @rodgz, @nnnnicholas, @wolegechu, @drosk, @ogis-sanae, @jiangbei168, @RayJKS, @you21979, @derekb123, @riyaadh-aziz, @jfrazier-eth, @19714, @sea-edge, @huduse, @mikkyude, @Gonzser, @Damnum, @haammidd, @lvndry, @Parrot7483, @ahmedalaahagag, @saadjhk, @g3k0, @ilovespectra, @martintorok, @DillonB07, @soaple, @paouvrard, @legercy135, @huuscloras, @hiro-v, @borakilicoglu, @ZeroEkkusu, @tzzzoz, @praveenzid, @frabrunelle, @albertzl, @darioodiazsala91, @RbRe145, @0xObsidian, @Win0818, @kavehmozafari1, @lvwvm, @aiaa5505, @Swipdaggoe, @dfrancoce, @javogel, @JeneaVranceanu, @PierreJeanjacquot, @ali8889, @godgiraffe, @harveynighy, @hypnosophy, @CarlosMartinez-USDA, @microraptor, @creatinglake, @vt92i, @Akaedes, @rgfh10, @iperfectapp, @tusharr1411, @yuanfeiz, @BertsLifee, @wangjiajun0806, @abaez, @yuedou, @ehis-io, @shonjs, @1krona, @bichanna, @SHA888, @strollinghome, @derek518, @tobyornottobe, @tuzhao, @marwahmanbir, @loicttn, @Bitnoober, @logonaut, @chengang21, @Guizr, @the-other-mariana, @jrmoreau, @fakemonkgin, @salamer, @Cepelli, @fuzzc0refox-kazuki-matsumoto, @apiviuw, @raghu04, @saulocamposi, @michaelsena, @dangoosby, @sTingley, @sanjaydatasciencedojo, @DUMIE505, @ordinarycas, @vngncnc, @cattmote, @om2c0de, @play1895, @nickbytes, @kainsteffen, @Janaka-Steph, @jluk, @universefeeler, @wout, @rayedsikder, @JesseAbram, @nkmry, @0xVesion, @ResearchPawn, @Bytesu, @magania, @pblivin0x, @samsonq, @mark-chainalysis, @hoffer, @jdnixx, @jordancclive, @avargas, @aphix, @pawarvijay, @umidao, @quantumlicht, @MAURONAMORIM, @korkmazmuhammet, @sgrauel, @Jackneill, @yajiya, @renqHIT, @iamscr1pty, @yl, @AC0DEM0NK3Y, @Quwamakindele, @metavalent, @matgioi
